# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2f19994ef4757ba8a50483827c9f6a071470aa3f1bfe426a9e035a2a6154a0f94fae1546e3e9c8827892e02ee437197592512e00f1fa01d856885a2844667b3

test:
  secret_key_base: d7fb36c4ffbcd7ea43f9388350b544ae82112a47d7f7bceabd7f9c1fbb60d0e89da3411d615c8a74134a96ff228997ffbb677d65193ed9255d61dee2d3da0945

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
